### ISSUE TITLE
Occasional OAuth2 Reauthorization

### ISSUE THREAD

**Issue by quinnaissance** [jeremyephron/simplegmail#48] opened 2021-08-04 00:20 UTC
This may be related to KrishGarg's issue. It seems that I am periodically required to re-authorize via the Google web interface, despite the readme saying this should only occur once. I looked at `gmail_token.json` and sure enough, it has been modified with a new `access_token`.

I can't tell why this is occurring; it doesn't seem to be at any consistent time interval. I printed the exception:
`<class 'oauth2client.client.HttpAccessTokenRefreshError'>`
But that's all I could get for now.

Edit: It's probably worth noting I initially thought this was occurring because my program was running the same loop for many hours without re-initiating Gmail() (I assumed this would cause the refresh tokens not to update), but I made it re-initiate every hour and this still seems to occur.

**Comment by KrishGarg** [comment] 2021-08-04 06:15
Yea I have the same issue. I googled about it and it needs to refresh the access token with the refresh token. I think the simplegmail module should have a system for this, but I am new with google APIs so I am not sure.

**Comment by Mr-Groch** [comment] 2021-09-09 18:42
I'm running this script in cron (every 30 minutes) so Gmail class is reinitialized each time and I also have problem with token expiring...

**Comment by Mr-Groch** [comment] 2021-11-05 21:07
@jeremyephron  unfortunately on 4.0.4 I had this issue 2 times in past 2 weeks:

```
Traceback (most recent call last):
  File "/volume1/homes/groch/dev/kindle-gmail-verify/kindle-gmail-verify.py", line 8, in <module>
    labels = gmail.list_labels()
  File "/opt/lib/python3.9/site-packages/simplegmail/gmail.py", line 562, in list_labels
    res = self.service.users().labels().list(
  File "/opt/lib/python3.9/site-packages/simplegmail/gmail.py", line 107, in service
    self.creds.refresh(Http())
  File "/opt/lib/python3.9/site-packages/oauth2client/client.py", line 545, in refresh
    self._refresh(http)
  File "/opt/lib/python3.9/site-packages/oauth2client/client.py", line 761, in _refresh
    self._do_refresh_request(http)
  File "/opt/lib/python3.9/site-packages/oauth2client/client.py", line 819, in _do_refresh_request
    raise HttpAccessTokenRefreshError(error_msg, status=resp.status)
oauth2client.client.HttpAccessTokenRefreshError: invalid_grant: Token has been expired or revoked.
```

And I had to run manually with `--noauth_local_webserver` option and reathorize...

**Comment by quinnaissance** [comment] 2021-11-15 21:45
@Mr-Groch @jeremyephron Unfortunately I have also still had this issue despite upgrading to 4.0.4. It doesn't occur very often but it's definitely still happening.

**Comment by jeremyephron** [comment] 2021-11-16 00:50
Hi @Mr-Groch @quinnaissance, sorry to hear there are intermittent issues. I will add a fix for this as soon as I can test it. Am I correct that to reproduce this you are just running the program for an extended duration, periodically making requests (every 15-30 minutes or so?). I will try to figure out the root issue.

**Comment by quinnaissance** [comment] 2021-11-16 01:40
@jeremyephron I'm using it for notifications related to a reddit bot. The program runs on a loop once per week in a particular time window of about 3-5 hours. However, simplegmail is only being called in two circumstances:

1. If a timer runs over an hour → the constructor will be called again (was using this to try token refreshing)
2. If a particular string pattern is found → a single email is sent, and then the program terminates.

On average I'd say I encounter this 1-2 times per 3-5 hour runtime. Like I said before, I don't think it's at a specific time interval although I could be wrong.

**Comment by Mr-Groch** [comment] 2021-11-16 08:11
I'm using simplegmail in simple python script running in cron every 30 minutes.

**Comment by lemminkeinen** [comment] 2022-04-10 14:40
Hi everyone!

I am new in gihub, python and google api, so my question might be solved but i cant get how or where. 

My script was running on VPS, so got in trouble that seems to be described here. Script suppose to run each 10 minutes, exactle in one week i got this:

**"Your browser has been opened to visit:

    https://accounts.google.com/o/oauth2/auth?...........(my personal api oath data i guess).........&access_type=offline&response_type=code

If your browser is on a different machine then exit and re-run this
application with the command-line parameter  --noauth_local_webservernex
"**

So i stucked on this moment.... Can somebody explain me what shoud be done next? If i run it on my home ps - Authorisation window is being opened, i pass it but i cant do the same on my VPS. 


Thanks, people.

**Comment by felciano** [comment] 2022-06-24 22:41
Hi folks just started using `simplegmail` inside of a `pandas` script that runs daily, and seem to have been bitten by this issue. Is the a current workaround or way to ensure the tokens are refreshed appropriately without forcing a new log in?

**Comment by quinnaissance** [comment] 2022-06-25 19:11
> Hi folks just started using `simplegmail` inside of a `pandas` script that runs daily, and seem to have been bitten by this issue. Is the a current workaround or way to ensure the tokens are refreshed appropriately without forcing a new log in?

Hello, I have yet to find a workaround unfortunately.

**Comment by felciano** [comment] 2022-07-12 23:08
Hi folks --

After some additional logging and testing, I can confirm what @lemminkeinen suggests: the token seems to expire after exactly one week. I wonder if this is running afoul of [limits imposed by Google for "unpublished" apps](https://support.google.com/cloud/answer/10311615#zippy=%2Ctesting):

> Authorizations by a test user will expire seven days from the time of consent. If your OAuth client requests [an offline access type](https://developers.google.com/identity/protocols/oauth2/web-server#offline) and receives a refresh token, that token will also expire.

Aside: @jeremyephron is there a particular reason you are using `oauth2client`? It has been [deprecated](https://pypi.org/project/oauth2client/) for several years in favor of `google-auth` ([link](https://google-auth.readthedocs.io/en/master/)). Most of the example code seems to use the newer libraries, so might be easier to diagnose going forward if the newer recommend libs were used.

**Comment by jeremyephron** [comment] 2023-03-12 23:19
Hey folks, a couple different issues being discussed here: auth failures within a week and expiry after a week.

@felciano correctly stated that unpublished apps will have their tokens expire after a week.

I have no been able to reproduce a quicker failure (e.g., I've had a script sending a message every 20-30 minutes for days on end with no failure).

Because it's been so long, I'm going to close this issue. Please open a new issue with more details on the failure and how to reproduce if this is an ongoing problem.

**Closed by jeremyephron** 2023-03-12 23:19 UTC
